import { Arvo } from "next/font/google";
import "@/app/globals.css";
import AdminNavbar from "@/components/AdminNavbar";
import ToastProvider from "@/components/ToastProvider";
const arvo = Arvo({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={arvo.className}>
        <main className="mx-auto">
          <AdminNavbar />
          <div className="pt-16 md:pt-14 md:ml-64 bg-gray-50 min-h-screen">
            {children}
          </div>
        </main>
        <ToastProvider />
      </body>
    </html>
  );
}
